#!/bin/bash
#SBATCH -J Unstructure_debug
#SBATCH -A ADCIRC
#SBATCH -o Unstructured_debug.o%j
#SBATCH -e Unstructured_debug.o%j
#SBATCH -p development
#SBATCH -N 2
#SBATCH -n 250
#SBATCH -t 00:15:00

#SBATCH --mail-user=markloveland@utexas.edu
#SBATCH --mail-type=begin        # email me when the job starts
#SBATCH --mail-type=end          # email me when the job finishes

date > run.timing
PYTHONPATH=/home1/04637/mdl2665/anaconda3
eval "$(/home1/04637/mdl2665/anaconda3/bin/conda shell.bash hook)" 
conda init
conda activate fenicsx-env
conda info
ibrun python3 Shoaling_unstructured_IC.py
date >> run.timing

